name: orbitforge
channels:
  - conda-forge
dependencies:
  - python=3.12
  - conda >=25.3.0
  - mamba >=2.1.1
  - pip
  - pydantic
  - pytorch
  - pytorch-cuda=12.4
  - torchvision
  - torchaudio
  - pytorch3d
  - pythonocc-core
  - torch-geometric
  - open3d
  - trimesh
  - meshio
  - wandb
  - hydra-core
  - dvc
  - dvc-s3
  - pip:
      - reportlab
